# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!

Quiz Game
"""

questions = ("Q1 How many elements are in periodic table?: ",
             "Q2 Which is softest metal of the periodic table?: ",
             "Q3 Which is the inert gas among these?: ",
             "Q4 In which column of periodic table inert gaese are found?: ",
             "Q5 How many planets are in our solar system?: ",
             "Q6 Which is the odd among these?: ",
             "Q7 How many bones are in human body?: ",
             "Q8 Which animal lays the largest egg?: ",
             "Q9 Which planet in the solar system is coldest?: ",
             "Q10 What is the factorial of 5 (5!)?: "
             )
options=(("A: 120", "B: 218", "C: 118", "D: 318"),
          ("A: Sodium(Na)", "B: Cesium(Cs)", "C: Iron(Fe)", "D: Aluminum(Al)"),
          ("A: O", "B: H", "C: N", "D: Xe"),
          ("A: 10", "B: 20", "C: 14", "D: 18"),
          ("A: 10", "B: 8", "C: 14", "D: 18"),
          ("A: Sodium(Na)", "B: Argon(Ar)", "C: Iron(Fe)", "D: Aluminum(Al)"),
          ("A: 106", "B: 206", "C: 146", "D: 186"),
          ("A: Elephant", "B: Whale", "C: Ostrich", "D: Duck"),
          ("A: Uranus", "B: Mars", "C: Venus", "D: Neptune"),
          ("A: 10", "B: 120", "C: 140", "D: 125"))
answers=("C", "B", "D", "D", "B", "B", "B", "C", "A", "B")
guesses=[]
score=0
question_num=0

for question in questions:
  print("--------------------------------")
  print(question)

  for option in options[question_num]:
    print(option)

  guess= input("Enter (A, B, C, D): ").upper()
  guesses.append(guess)
  if guess==answers[question_num]:
    score+=1
    print("--Correct!--")
  else:
    print("--Incorrect!--")
    print(f"{answers[question_num]} is the correct answer")
  question_num+=1



print("------------------------------------")
print("----------Result--------------------")
print("------------------------------------")

print("answers: ", end="")

for answer in answers:
  print(answer, end=" ")
print()

print("guess: ", end="")
for guess in guesses:
  print(guess, end=" ")

print()

score=int(score/len(questions)*100)

print(f"Your score is {score}%")